#!/usr/bin/env node
'use strict';

const grpc = require('@grpc/grpc-js');
const protoLoader = require('@grpc/proto-loader');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const PROTO_PATH = path.join(ROOT, 'freeswitch_api.proto');
const TARGET = process.env.TARGET || '127.0.0.1:50051';
const DEADLINE_MS = positiveInteger(process.env.DEADLINE_MS, 5000);

const modeValues = {
  compat: 'RESPONSE_MODE_COMPAT',
  raw: 'RESPONSE_MODE_RAW_ONLY',
  structured: 'RESPONSE_MODE_STRUCTURED_ONLY'
};

function positiveInteger(value, fallback) {
  const parsed = Number.parseInt(value || '', 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
}

function usage() {
  console.error(
    'Usage: node examples/node/client.js <command> [arguments] [compat|raw|structured]\n' +
    'Examples:\n' +
    '  node examples/node/client.js version\n' +
    '  node examples/node/client.js status "" raw\n' +
    '  node examples/node/client.js show \"channels as json\" structured\n' +
    '  node examples/node/client.js bgapi \"originate user/1001 &bridge(user/1002)\" raw'
  );
}

const command = process.argv[2];
const args = process.argv[3] || '';
const modeName = (process.argv[4] || 'compat').toLowerCase();

if (!command || !Object.prototype.hasOwnProperty.call(modeValues, modeName)) {
  usage();
  process.exit(2);
}

const packageDefinition = protoLoader.loadSync(PROTO_PATH, {
  keepCase: false,
  longs: String,
  enums: String,
  defaults: true,
  oneofs: true
});
const fsgrpc = grpc.loadPackageDefinition(packageDefinition).fsgrpc;
const client = new fsgrpc.FreeSwitchApi(
  TARGET,
  grpc.credentials.createInsecure()
);
const executeRpc = client.execute || client.Execute;
if (typeof executeRpc !== 'function') {
  throw new Error('Execute RPC method was not generated by @grpc/proto-loader');
}

const request = {
  command,
  arguments: args,
  responseMode: modeValues[modeName]
};
const options = {
  deadline: new Date(Date.now() + DEADLINE_MS)
};

executeRpc.call(client, request, options, (error, response) => {
  client.close();

  if (error) {
    console.error(JSON.stringify({
      grpcCode: error.code,
      grpcStatus: grpc.status[error.code] || 'UNKNOWN',
      details: error.details || error.message
    }, null, 2));
    process.exit(1);
  }

  console.log(JSON.stringify(response, null, 2));
  process.exit(response.success ? 0 : 3);
});
