#!/usr/bin/env node
'use strict';

const grpc = require('@grpc/grpc-js');
const protoLoader = require('@grpc/proto-loader');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const PROTO_PATH = path.join(ROOT, 'freeswitch_api.proto');

function integerEnv(name, fallback, minimum = 1) {
  const parsed = Number.parseInt(process.env[name] || '', 10);
  if (!Number.isFinite(parsed) || parsed < minimum) {
    return fallback;
  }
  return parsed;
}

const config = {
  target: process.env.TARGET || '127.0.0.1:50051',
  concurrency: integerEnv('CONCURRENCY', 32),
  totalRequests: integerEnv('TOTAL_REQUESTS', 10000),
  warmupRequests: integerEnv('WARMUP_REQUESTS', 100, 0),
  deadlineMs: integerEnv('DEADLINE_MS', 5000),
  command: process.env.COMMAND || 'version',
  arguments: process.env.ARGUMENTS || '',
  responseMode: process.env.RESPONSE_MODE || 'RESPONSE_MODE_RAW_ONLY'
};

const packageDefinition = protoLoader.loadSync(PROTO_PATH, {
  keepCase: false,
  longs: String,
  enums: String,
  defaults: true,
  oneofs: true
});
const fsgrpc = grpc.loadPackageDefinition(packageDefinition).fsgrpc;
const client = new fsgrpc.FreeSwitchApi(
  config.target,
  grpc.credentials.createInsecure()
);
const executeRpc = client.execute || client.Execute;
if (typeof executeRpc !== 'function') {
  throw new Error('Execute RPC method was not generated by @grpc/proto-loader');
}

function executeOnce(recordLatency) {
  const started = process.hrtime.bigint();
  const request = {
    command: config.command,
    arguments: config.arguments,
    responseMode: config.responseMode
  };
  const options = {
    deadline: new Date(Date.now() + config.deadlineMs)
  };

  return new Promise((resolve) => {
    executeRpc.call(client, request, options, (error, response) => {
      const elapsedMs = Number(process.hrtime.bigint() - started) / 1e6;
      resolve({ error, response, elapsedMs: recordLatency ? elapsedMs : null });
    });
  });
}

async function warmup() {
  let claimed = 0;
  const workers = Array.from(
    { length: Math.min(config.concurrency, config.warmupRequests || 1) },
    async () => {
      while (true) {
        const id = claimed++;
        if (id >= config.warmupRequests) {
          return;
        }
        await executeOnce(false);
      }
    }
  );
  await Promise.all(workers);
}

function percentile(sortedValues, percentileValue) {
  if (sortedValues.length === 0) {
    return 0;
  }
  const index = Math.min(
    sortedValues.length - 1,
    Math.max(0, Math.ceil((percentileValue / 100) * sortedValues.length) - 1)
  );
  return sortedValues[index];
}

async function run() {
  console.log('mod_grpc_api stress test');
  console.log(JSON.stringify(config, null, 2));

  if (config.warmupRequests > 0) {
    console.log(`Running ${config.warmupRequests} warm-up request(s)...`);
    await warmup();
  }

  const counters = {
    completed: 0,
    commandSuccess: 0,
    commandFailure: 0,
    resourceExhausted: 0,
    unavailable: 0,
    deadlineExceeded: 0,
    otherTransportFailure: 0
  };
  const latencies = [];
  let claimed = 0;
  const started = process.hrtime.bigint();

  const workers = Array.from({ length: config.concurrency }, async () => {
    while (true) {
      const requestId = claimed++;
      if (requestId >= config.totalRequests) {
        return;
      }

      const result = await executeOnce(true);
      counters.completed += 1;
      latencies.push(result.elapsedMs);

      if (result.error) {
        if (result.error.code === grpc.status.RESOURCE_EXHAUSTED) {
          counters.resourceExhausted += 1;
        } else if (result.error.code === grpc.status.UNAVAILABLE) {
          counters.unavailable += 1;
        } else if (result.error.code === grpc.status.DEADLINE_EXCEEDED) {
          counters.deadlineExceeded += 1;
        } else {
          counters.otherTransportFailure += 1;
        }
      } else if (result.response && result.response.success) {
        counters.commandSuccess += 1;
      } else {
        counters.commandFailure += 1;
      }
    }
  });

  await Promise.all(workers);
  const durationSeconds = Number(process.hrtime.bigint() - started) / 1e9;
  latencies.sort((a, b) => a - b);

  const attemptedTps = counters.completed / durationSeconds;
  const successfulTps = counters.commandSuccess / durationSeconds;

  console.log('\nResults');
  console.log(`Duration seconds:          ${durationSeconds.toFixed(3)}`);
  console.log(`Completed:                 ${counters.completed}`);
  console.log(`Command success:           ${counters.commandSuccess}`);
  console.log(`Command failure:           ${counters.commandFailure}`);
  console.log(`RESOURCE_EXHAUSTED:        ${counters.resourceExhausted}`);
  console.log(`UNAVAILABLE:               ${counters.unavailable}`);
  console.log(`DEADLINE_EXCEEDED:         ${counters.deadlineExceeded}`);
  console.log(`Other transport failures:  ${counters.otherTransportFailure}`);
  console.log(`Attempted throughput:      ${attemptedTps.toFixed(2)} req/s`);
  console.log(`Successful throughput:     ${successfulTps.toFixed(2)} req/s`);
  console.log(`Latency p50:               ${percentile(latencies, 50).toFixed(2)} ms`);
  console.log(`Latency p95:               ${percentile(latencies, 95).toFixed(2)} ms`);
  console.log(`Latency p99:               ${percentile(latencies, 99).toFixed(2)} ms`);
  console.log(`Latency max:               ${(latencies.length ? latencies[latencies.length - 1] : 0).toFixed(2)} ms`);

  client.close();

  const unexpectedFailures =
    counters.commandFailure +
    counters.deadlineExceeded +
    counters.otherTransportFailure;
  process.exitCode = unexpectedFailures === 0 ? 0 : 1;
}

run().catch((error) => {
  client.close();
  console.error(error && error.stack ? error.stack : error);
  process.exitCode = 1;
});
